DROP DATABASE GPABook;

CREATE DATABASE GPABook;
USE GPABook;

CREATE TABLE IF NOT EXISTS UNIVERSITY(
UniID INT NOT NULL AUTO_INCREMENT,
UniName varchar(25) NOT NULL,
PRIMARY KEY(UniID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT(
ID INT NOT NULL AUTO_INCREMENT,
Email varchar(50) NOT NULL,
Password varchar(25) NOT NULL,
AccountType INT,
PRIMARY KEY(ID) 
);

CREATE TABLE IF NOT EXISTS FACULTY(
FacultyID INT NOT NULL AUTO_INCREMENT,
FacName varchar(25) NOT NULL,
UniID INT NOT NULL,
PRIMARY KEY(FacultyID),
FOREIGN KEY (UniID) REFERENCES UNIVERSITY(UniID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DEPARTMENT(
DepartmentID INT NOT NULL AUTO_INCREMENT,
DName varchar(100) NOT NULL,
FacultyID INT NOT NULL,
PRIMARY KEY(DepartmentID),
FOREIGN KEY (FacultyID) REFERENCES FACULTY(FacultyID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS STUDENT(
StudentId INT NOT NULL AUTO_INCREMENT,
ID INT NOT NULL,
FName varchar(40) NOT NULL,
Initials varchar(10) NOT NULL,
LName varchar(20) NOT NULL,
Eno varchar(10) NOT NULL,
Gender TINYINT(1) NOT NULL, 		# Male = 1, Female = 0;
UniID INT NOT NULL,
FacultyID INT NOT NULL,
Batch INT NOT NULL,
PhotoID varchar(10),
PRIMARY KEY(StudentId),
FOREIGN KEY (ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (UniID) REFERENCES UNIVERSITY(UniID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (FacultyID) REFERENCES FACULTY(FacultyID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS COURSES(
CourseId INT NOT NULL AUTO_INCREMENT,
CourseCode varchar(10) NOT NULL,
CourseName varchar(50) NOT NULL,
DepartmentID INT NOT NULL,
Credits TINYINT(3),
Elective TINYINT(1) DEFAULT 0,
PrereqID INT DEFAULT NULL,
Semester TINYINT(3),
NonGPA TINYINT(1) DEFAULT 0,
PRIMARY KEY(CourseId),
FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (PrereqID) REFERENCES COURSES(CourseId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GPA(
StudentId INT NOT NULL,
CourseId INT NOT NULL,
GPA Decimal(2,1) NOT NULL,
PRIMARY KEY(StudentId, CourseId),
FOREIGN KEY (StudentId) REFERENCES STUDENT(StudentId) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CourseId) REFERENCES COURSES(CourseId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS FRIEND(
StudentId INT NOT NULL,
FriendID INT,
PRIMARY KEY(StudentId),
FOREIGN KEY (StudentId) REFERENCES STUDENT(StudentId) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (FriendID) REFERENCES STUDENT(StudentId) ON DELETE CASCADE ON UPDATE CASCADE
);

show tables;